### ISSUE TITLE
Can't get it installed right

### ISSUE THREAD

**Issue by lipe123** [3RaGaming/Web_Control#39]
Hey there

Sorry to bother but I've been searching for a nice server manager and wanted to give this one a try.

I have two issues (I think)

1. I don't know how to set up apache with ssh, I can set up the default http but no idea on https, is there no way around this?
2. when running the script I kept getting errors about if loop variables and environment C11 or C99 that needed so i changed the script to: gcc-std=C99 -o bla bla which made those go away.
Then I still got  a bunch of pointer errors and well with no https login I got nowhere.

Mind giving some more noob-friendly help in the setup readme?

I'm running debian 8 x64

**Comment by zackman0010** [comment]
For question 1, I can tell you that there isn't a way around it. The code is set to only run on an HTTPS page. @stuudmuffin should be able to tell you how to enable this, as he's the one who hosts ours.
Question 2 is going to be my realm. We discovered that on non-Ubuntu systems, you had to compile with `--std=gnu99`. We unfortunately forgot to edit our instructions to put that in there. If you use this std and still have errors, then let me know.

**Comment by zackman0010** [comment]
There are also a few other config options that we haven't quite written up the documentation for. I plan on getting this documentation written soon.

**Comment by lipe123** [comment]
Thanks for that part, it now compiles properly and I realized i had installed php5 instead of 7, so I removed 5 and followed a guide to install 7, all that done.
Enabled ssh and everything but still just see "refused to connect".

**Comment by stuudmuffin** [comment]
Are you using apache or httpd/nginx?
Since ubuntu is debian based, i'm going to first assume apache.
If apache is already working non ssl, these are the commands to enable ssl:
 sudo a2enmod ssl
sudo a2ensite default-ssl
systemctl reload apache2

This will enable SSL under a "self signed" ssl certificate. To get the web control working properly with discord auth, a vaild SSL certificate is required. We are using www.sslforfree.com for ours, and have so far had success. Once after a regeneration, discord claimed it didn't like it anymore... but a second regeneration got it working again. Follow the steps on sslforfree to obtain some ssl certificates from them, then put them into the /etc/ssl/certs folder (you'll only need the .key and .pem files). Once they are in there, edit your /etc/apache2/sites-enabled/default-ssl.conf file to point to the respective file locations for the configuration items "SSLCertificateFile" and "SSLCertificateKeyFile"

Run the systemctl reload apache2 command again and your site should be running on "certified" ssl.
or, you could just use the altlogin.php, with user names and passwords MD5 hashed in the /var/www/users.txt file to bypass discord logins. 

Sorry for the hassle. We're still in the process of getting the install process streamlined, and allowing better configuration and control of how a web_control server is setup. 

Let me know how these steps work for you?

**Comment by lipe123** [comment]
Thanks a ton man, I already had the first step working but the default-ssl part was the real kicker. 
Login page comes up now 😄 
Oh and yes i was using apache

Idc about a real cert, i just ignore the warning and continue. I'll play with this more tomorrow and see how far I get.

**Comment by zackman0010** [comment]
I'll hopefully get the rest of the config instructions typed up tomorrow evening. Things that'll be required for the bot to run properly.

**Comment by lipe123** [comment]
Okay so now that I have login working, when I do log in with discord I get "unknown error" and when I login with altlogin.php I get:
Error in server selection index.php
The url just shows: ?d=server1 after my IP when I log in.

I'm thinking there is probably some permissions issues as well because I had to sudo the commands all the files are set to owner/user root now.
Does that all need to be changed to www-data for apache to access/run things?

**Comment by zackman0010** [comment]
Yes, permissions will need to be `www-data`. The rest of the details will be in the instructions document I'm going to be typing up in a few hours. I'll reply here when I have it finished.

**Comment by lipe123** [comment]
No rush just wanted to put that but in there in case it causes other issues that might be missed.

Thanks for all the help/patience sofar.

**Comment by zackman0010** [comment]
It's not a problem. Some of these things are long overdue, such as this instruction document. Lol
Permissions problems will be trouble, we've experienced that before. The installer is supposed to set up a cron task that automatically adjusts all permissions by setting the owner to `www-data` every so often, but it appears that step isn't working properly.

**Comment by lipe123** [comment]
Yes I noticed an error at the cronjob part as well but figured thats small problems compared to the rest haha.

**Comment by stuudmuffin** [comment]
I'll be tackling the proper install of the crontab as I update the install.sh as well. When I set out to get install.sh up to par, I got distracted in discovering I could add installing new server versions with a click of a button in the web control. I've diverted my attention to that, and will resume the install.sh re-work when I finish.

Soon, install.sh will be a one stop place to install and update the web control from command line

**Comment by zackman0010** [comment]
[Web Control Configuration.pdf](https://github.com/3RaGaming/Web_Control/files/997972/Web.Control.Configuration.pdf)
First version of our config instructions document. Let me know how these instructions turn out for you, please, or if there's any further detail I need to include.

**Comment by lipe123** [comment]
Had a quick look through it and of course I have nothing of that set up at the moment, I'll start getting the discord things sorted out first.
I wasn't aware discord played such a big role in this.

Is there any way to have the factorio server and saves paths as config options also?

**Comment by zackman0010** [comment]
Not at the moment, unfortunately. That's another thing that is still in the works. As for Discord, a version of web control that doesn't use it is also planned. Just not finished. We have a lot of things along those lines. lol

**Comment by zackman0010** [comment]
The benefit of Discord, though, is that the program transmits chat back and forth between Factorio servers and your Discord server. So you can monitor your player's chat from the Discord server, watch for griefers, etc. It also allows banning players by typing a command in Discord.

**Comment by lipe123** [comment]
I can't find any good info with a quick search but does the built in rcon system not provide a similar thing for chat and commands?

**Comment by zackman0010** [comment]
No, it doesn't. Not in a way that allows us to do it from Discord. That's why we had to create the management program, as it does the work of transmitting chat for us.

**Comment by zackman0010** [comment]
I think we may have a version that doesn't require the bot by this time next week. Until then, however, the Discord bot will be required.

**Comment by lipe123** [comment]
Sorry it took me so long to reply, I started going through your guide and got a bot set up but I don't host factorio on my windows machine.
I have a dedicated linux machine with no screen or anything just SSH shell. How do I do the server adding and all that fun stuff from that side?

**Comment by zackman0010** [comment]
Hey, sorry for the delay. I've had so many chores around the house recently that I've barely had time to sit down at my computer. Lol
What exactly are you having trouble setting up at the moment? Everything in the guide I linked should be able to be done on any platform, as long as the config.json file is put onto the Linux server where the program is hosted.

**Comment by lipe123** [comment]
No worries, pretty busy here too and just running server manually atm.
I don't know how to get the discord stuff loaded on the server, its a linux machine with no GUI.
Not even sure if I need it installed or not.

**Comment by zackman0010** [comment]
No, you don't need to have Discord installed on the Linux machine. You can create a Discord server from any machine.

**Comment by stuudmuffin** [comment]
We really need to implement a way to have the discord server disabled...

We are working on revising some things so install is easier, this being one of them. To setup a discord server, go to  www.discordapp.com. Once you have an account created, creating a free server is pretty easy. We might have a simple guide setup somewhere we can link to. We're in the mad process of getting the entire install process cleaned up. 

Let us know when you have a discord server created. For starters, the server ID will be stored in /var/www/factorio/config.json

There are a few other things inside that config.json file we will need to configure. But we'll get to those in a moment (and if I can find that install pdf i think we have laying around)

**Comment by stuudmuffin** [comment]
Assuming resolved
