### ISSUE TITLE
Attempting to start a second server returns "Error In Input"

### ISSUE THREAD

**Issue by AlienXAXS** [3RaGaming/Web_Control#48]
Hi Guys,
I got the software working, seems great so far.

I have attempted to make a 2nd server instance by copying server1 to server2 and deleting the logs and reconfiguring the server config json file.

However, when clicking the Start button on this server, i got "Error In Input" as a Javascript Alert Dialog.

Any ideas?

**Comment by stuudmuffin** [comment]
be sure to also change the config/config.ini to point to the correct write-data path. This might be one reason. As for it appearing as a javascript alert though...

**Comment by AlienXAXS** [comment]
Looking into this further, my server folder had a hyphen in it "agn-factory".

Removing the hyphen fixed the issue, however i am unsure why manage.sh is throwing the error if there is a hyphen there.

**Comment by stuudmuffin** [comment]
it's sanitizing the input, keeping only alphanumeric characters. Since manage.sh is a shell script, it has full access to the operating system. I was being as careful as I could to not allow malicious code to be injected into it.
